name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # optional flags:
          # SECTION_NAME: ""
          # COMMIT_BY_ME: "True"
          # COMMIT_MESSAGE: "True"
          # COMMIT_USERNAME: "drekunia"
          # COMMIT_EMAIL: "drekunia@gmail.com"
          # SHOW_UPDATED_DATE: "True"
          # UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "True"
          # SHOW_TOTAL_CODE_TIME: "False"
          # SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT_FLAG: "False"
          SHOW_DAYS_OF_WEEK: "False"
          # SHOW_LANGUAGE: "False"
          # SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          # SHOW_EDITORS: "False"
          # SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          # SHOW_LOC_CHART: "False"
          # IGNORED_REPOS: "drekunia-obsidian-vault"
          # SYMBOL_VERSION: 1
          # DEBUG_LOGGING: "True"
